// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2bYF0-wDYCWV8NN91iD8LzGCYPie2q4',
    appId: '1:824703094873:android:6f32f0fa5a61a4336ea148',
    messagingSenderId: '824703094873',
    projectId: 'chat-mingle-4db84',
    storageBucket: 'chat-mingle-4db84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJF3BYJpD7ircVJ4YrQDRrMbZ1aYkw9Mk',
    appId: '1:824703094873:ios:bfb92dfd8925971a6ea148',
    messagingSenderId: '824703094873',
    projectId: 'chat-mingle-4db84',
    storageBucket: 'chat-mingle-4db84.appspot.com',
    androidClientId: '824703094873-tuh6hrf873d8aacv3ekjup2bee8kopdr.apps.googleusercontent.com',
    iosClientId: '824703094873-77v10a1ki941qsjpjtsrcvpj216hmarf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMingle',
  );
}
